services:
  socialapp.api:
    image: socialapp.api
    ports:
      - "5212:8080"
    build:
      context: .
      dockerfile: SocialApp.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=mongodb://root:example@mongodb:27017
      - ConnectionStrings__UserStorage=Server=db;port=3306;database=users;user id=admin;password=admin

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - user_data:/var/lib/mysql

volumes:
  mongo-data:
  mongo-config:
  user_data: