# This is a generated file. Not intended for manual editing.
services:
  socialapp.api:
    build:
      context: "C:\\Users\\Taras Sharko\\Desktop\\SocialApp\\SocialApp"
      dockerfile: "SocialApp.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/SocialApp.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "socialapp.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Taras Sharko\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Taras Sharko\\Desktop\\SocialApp\\SocialApp\\SocialApp.Api:/app:rw"
    - "C:\\Users\\Taras Sharko\\Desktop\\SocialApp\\SocialApp:/src:rw"
    working_dir: "/app"
