POST localhost:5212/api/Posts
Content-Type: application/json

{
  "Title": "Test2",
  "Content": "Я зараз буду битись головою об стінку"
}

###

GET localhost:5212/api/Posts

###

GET localhost:5212/api/Posts/fake